import type { NextPage } from 'next'
import Head from 'next/head';

const Message: NextPage = () => {
   return (
      <div className='flex'>
         <Head>
            <title>Chat App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div>Message chat</div>
      </div>
   )
}

export default Message;
