import type { NextPage } from 'next'
import Head from 'next/head';

const Phones: NextPage = () => {
   return (
      <>
         <Head>
            <title>Chat App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div>Phone Page</div>
      </>
   )
}

export default Phones;
